# Generated by Django 3.0.4 on 2020-04-15 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_test', models.CharField(max_length=100)),
                ('module1_advantages', models.CharField(max_length=100)),
                ('module1_obstacles', models.CharField(max_length=100)),
                ('module1_extra_advantage', models.CharField(max_length=100)),
                ('module1_extra_obstacles', models.CharField(max_length=100)),
                ('module2_selections', models.CharField(max_length=100)),
                ('module2_extra_need', models.CharField(max_length=100)),
                ('module3_selections', models.CharField(max_length=100)),
                ('module3_extra_value', models.CharField(max_length=100)),
                ('module4_selection_1', models.CharField(max_length=100)),
                ('module4_selection_2', models.CharField(max_length=100)),
                ('module6_selection', models.CharField(max_length=100)),
                ('module7_feedback', models.IntegerField(default=999)),
                ('after_test', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='Date')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.DeleteModel(
            name='UserHistory',
        ),
        migrations.AddField(
            model_name='userdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.User'),
        ),
    ]
