# Generated by Django 3.0.4 on 2020-04-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200415_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='module7_feedback',
        ),
        migrations.AddField(
            model_name='userdata',
            name='module5_personal',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='module5_work',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
