# Generated by Django 3.0.4 on 2020-04-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200423_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='module1_extra_advantage',
            new_name='module1_extra',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='module1_extra_obstacles',
        ),
        migrations.AddField(
            model_name='userdata',
            name='current',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='finished',
            field=models.CharField(default='false,false,false,false,false,false,false,false,false,false', max_length=100),
            preserve_default=False,
        ),
    ]
