# Generated by Django 3.0.4 on 2020-05-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200430_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='module4_selection_1',
            new_name='module4_selections_1',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='module4_selection_2',
            new_name='module4_selections_2',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='module6_selection',
            new_name='module6_selections',
        ),
        migrations.AddField(
            model_name='userdata',
            name='module5_personal_selections',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdata',
            name='module5_work_selections',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
